name: Convert Markdown to PDF

on:
  push:
    branches:
      - main  # Adjust this to your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js and npm
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install md-to-pdf
        run: npm install -g md-to-pdf

      - name: Create output folder
        run: mkdir -p _output

      - name: Convert Markdown to PDF
        run: |
          
          for f in *.md; do
            cat $f
            echo
          done | md-to-pdf > ../_output/result.pdf

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v2
        with:
          name: pdf-output
          path: _output/result.pdf
