name: Convert Markdown to PDF

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Node.js and npm
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install markdown-pdf
        run: npm install -g markdown-pdf@latest
      - name: Create output folder
        run: mkdir -p _output
      - name: Convert Markdown to PDF
        run: |
          for f in *.md; do
            markdown-pdf $f -o _output/${f%.md}.pdf
          done
      - name: Upload PDF artifact
        uses: actions/upload-artifact@v3
        
        with:
          name: pdf-output
          path: _output/result.pdf
