name: Merge PDFs Workflow
on:
  push:
    branches:
      - main
jobs:
  merge-pdfs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Merge PDFs
        uses: elMuso/MergePDFs-action@1.1
        with:
          path: ./
          filename: azure-notes
