name: Create PDF

on: push


jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: |
          mkdir output  # create output dir
          # this will also include README.md
          echo "FILELIST=$(printf '"%s" ' *.md)" >> $GITHUB_ENV
      - uses: docker://pandoc/latex:2.9
        with:
          args: --output=output/result.pdf ${ env.FILELIST }
      - uses: actions/upload-artifact@v2
        with:
          name: output
          path: output
